---
version: 0.2

phases:
  pre_build:
    commands:
      - yum install -y tar wget unzip sudo
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.4.1/packer_1.4.1_linux_amd64.zip && unzip packer.zip
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py
      - pip install awscli
      - aws --version
      - curl -qL -o aws_credentials.json http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - chmod 700 hashicorp/init-scripts/*.sh
  build:
    commands:
      - chmod 700 build.sh
      # - ./build.sh hashicorp/solodev-php-56/windows-2016/config solodev-windows-2016-php56.json
      - ./build.sh hashicorp/solodev-php-72/windows-2016/config solodev-windows-2016-php72.json
  post_build:
    commands:
      - sudo hashicorp/init-scripts/cleanup.sh
      - echo "HashiCorp Packer build completed on `date`"